name: pr_check

on:
  workflow_dispatch:
    

jobs:
  build_and_test:
    runs-on: [self-hosted]
    container: ubuntu:latest
    steps:
      - name: mkdir test-pr-CSAPP
        run: |
          pwd
          ls
          whoami         

