name: pr_check

on:
  workflow_dispatch:
    

jobs:
  build_and_test:
    runs-on: [self-hosted]
    steps:
      - name: mkdir test-pr-CSAPP
        run: |
          pwd
          ls
          whoami         
          sudo groupadd docker && \
          sudo usermod -aG docker "$(whoami)" && \
          newgrp docker
          docker run hello-world

