name: pr_check

on:
  workflow_dispatch:
    

jobs:
  build_and_test:
    runs-on: [self-hosted]
    steps:
      - name: mkdir test-pr-CSAPP
        run: |
          pwd
          ls
          whoami
          sudo service docker start
          sudo usermod -aG docker ubuntu
          newgrp docker
          sudo docker container ls

