name: pr_check

on:
  workflow_dispatch:
    

jobs:
  build_and_test:
    runs-on: [self-hosted]
    container:
      image: matrixdb/centos7_build:latest
      options: --privileged
    steps:
      - name: mkdir test-pr-CSAPP
        run: |
          pwd
          mkdir test-pr-CSAPP
          ls

