name: pr-integration

# ! Can be only triggered by comment `/integration`

on:
  repository_dispatch:
    types: [integration-command]


jobs:
  execute:
    run: |
      echo "yes"

  report_on_success:
    if: ${{ success() }}
    needs: [execute]
    runs-on: ubuntu-20.04
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          message: |
            ✅ Intergration passed
          pr_number: ${{ github.event.client_payload.pull_request.number }}

  report_on_failure:
    if: ${{ failure() }}
    needs: [execute]
    runs-on: ubuntu-20.04
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          message: |
            ❌ Intergration failed
          pr_number: ${{ github.event.client_payload.pull_request.number }}

  report_on_cancel:
    if: ${{ cancelled() }}
    needs: [execute]
    runs-on: ubuntu-20.04
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          message: |
            🚫 Intergration cancelled
          pr_number: ${{ github.event.client_payload.pull_request.number }}
