name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    if: ${{ github.event.issue.pull_request }} # we handle comments in a PR
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: |
            integration
